### ISSUE TITLE
not activating indentation error

### ISSUE THREAD

**Issue by hr1jul** [blender-for-science/anton#4]
Traceback (most recent call last):
  File "F:\all_software\2.90.1\blender-2.91.0-21fec9513969-windows64\2.91\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\Hrijul\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\anton-master\__init__.py", line 46, in <module>
    from .visualizer import Anton_OT_Visualizer
  File "C:\Users\Hrijul\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\anton-master\visualizer.py", line 98
    vertices, faces, normals, _ = measure.marching_cubes(data)
    ^
IndentationError: unexpected unindent

just try installing in a window10
![image](https://user-images.githubusercontent.com/72699438/95683918-ad80b900-0c0b-11eb-96f8-15fdf163f474.png)

**Comment by imsenthur** [comment]
Fixed the issue, download the latest release [here](https://github.com/blender-for-science/anton/releases/tag/v0-2-1).

**Comment by hr1jul** [comment]
Thank  you bhaiya 😀😀😀😀
